### ISSUE TITLE
IdsTag: reattach has issues on the positioning of tags 

### ISSUE THREAD

**Issue by glenlieorillo** [infor-design/enterprise-wc#2135] opened 2024-03-27 13:22 UTC
**Describe the bug**
After reattaching the code, the tags are rearranged. Related to https://github.com/infor-design/enterprise-wc/issues/2040.

**To Reproduce**

1. Go to https://main.wc.design.infor.com/ids-tag/example.html
2. Open console
3. Paste the code to the console
`(function() { const container = document.querySelector("ids-tag"); const parent = container.parentNode; parent.removeChild(container); parent.appendChild(container); })()`
4. Notice the changing position of tags

**Expected behavior**

**Version**

- ids-enterprise: [e.g. v4.9.0 or v4.10.0]

**Screenshots**

https://github.com/infor-design/enterprise-wc/assets/102151352/4bc4ff44-2d84-4f0e-9835-f37d59bf7f24

**Platform**
 - Infor Application/Team Name: [e.g. Infor XYZ, Infor ABC]
 - Device: (if applicable) [e.g. iPhone 6 or Samsung Galaxy S6]
 - OS Version: [e.g. Windows 10 or iOS 8]
 - Browser Name: [e.g. chrome, safari, stock browser]
 - Browser Version: [e.g. 22, 66.0.3359.181 (Official Build) (64-bit)]

**Additional context**

**Comment by jdilag90** [comment] 2024-05-07 20:44
@glenlieorillo @tmcconechy 
Can we close this ticket?
The issue is in the reattach code provided in the instructions. 
It's detaching and re-appending the first `ids-tag`, that's why it's out of order

```
(function() {
   const container = document.querySelector("ids-tag"); // first ids-tag in DOM
   const parent = container.parentNode;
   parent.removeChild(container);
   parent.appendChild(container);
})()
```

Run the snippet below instead, it reattaches `ids-container`.
It shows that IdsTag works correctly after reattachment
```
(function () {
      const container = document.querySelector("ids-container");
      const parent = container.parentNode;
      parent.removeChild(container);
      parent.appendChild(container); 
})()
```

**Comment by tmcconechy** [comment] 2024-05-08 12:55
@jdilag90 I agree. lets close. can you reconfirm on your end @jbrcna

**Closed by tmcconechy** 2024-05-08 12:55 UTC
Labels: type: bug :bug:, [2], reattach issues

**Comment by glenlieorillo** [comment] 2024-05-08 13:34
Thanks for clarifying, @jdilag90. We can now close this ticket.

**Comment by jbrcna** [comment] 2024-05-13 03:54
> @jdilag90 I agree. lets close. can you reconfirm on your end @jbrcna


@tmcconechy apologies for late reply I was on leave.
confirmed. this is now working as expected when ids-container is used. please close the ticket
<img width="1722" alt="image" src="https://github.com/infor-design/enterprise-wc/assets/56722184/f353760a-1bbf-49e0-a348-3bacd2ded315">
