### ISSUE TITLE
IdsBreadcrumb: Truncated Breadcrumb Menu is broken

### ISSUE THREAD

**Issue by EdwardCoyle** [infor-design/enterprise-wc#831] opened 2022-08-02 14:35 UTC
Not sure where this fits so putting it here: But noticed that on https://main.wc.design.infor.com/ids-breadcrumb/truncated.html the popup doesnt open right (cut off). Maybe see if we need an issue?

_Originally posted by @tmcconechy in https://github.com/infor-design/enterprise-wc/issues/769#issuecomment-1178089616_

**Comment by tmcconechy** [comment] 2022-08-31 21:09
duplicate of https://github.com/infor-design/enterprise-wc/issues/906

**Closed by tmcconechy** 2022-08-31 21:09 UTC
Labels: type: bug :bug:, [2]
