### ISSUE TITLE
IdsFilterField: Filterfield borders are not aligned in Safari - BETA 1.3

### ISSUE THREAD

**Issue by glenlieorillo** [infor-design/enterprise-wc#2558] opened 2024-07-09 09:50 UTC
**Describe the bug**
Filterfield borders are not aligned in Safari.

**To Reproduce**

1. Go to https://main.wc.design.infor.com/ids-filter-field/example.html
2. Notice `filterfield` border
3. See error

**Expected behavior**

**Version**

- ids-enterprise: [e.g. v4.9.0 or v4.10.0]

**Screenshots**
![image](https://github.com/infor-design/enterprise-wc/assets/102151352/a50b5d30-643e-41a8-9263-05bfcf2f4370)

**Platform**
 - Infor Application/Team Name: [e.g. Infor XYZ, Infor ABC]
 - Device: (if applicable) [e.g. iPhone 6 or Samsung Galaxy S6]
 - OS Version: [e.g. Windows 10 or iOS 8]
 - Browser Name: [e.g. chrome, safari, stock browser]
 - Browser Version: [e.g. 22, 66.0.3359.181 (Official Build) (64-bit)]

**Additional context**

**Comment by tmcconechy** [comment] 2024-07-09 11:04
Duplicate of https://github.com/infor-design/enterprise-wc/issues/2522

**Closed by tmcconechy** 2024-07-09 11:04 UTC
Labels: type: bug :bug:, status: duplicate :twisted_rightwards_arrows:, [1]
