### ISSUE TITLE
IdsFieldFilter: field not aligned in Safari

### ISSUE THREAD

**Issue by jbrcna** [infor-design/enterprise-wc#2537] opened 2024-07-08 05:43 UTC
**Describe the bug**

**To Reproduce**

1. Go to (https://main.wc.design.infor.com/ids-filter-field/example.html)
3. See error

**Expected behavior**

**Version**

- ids-enterprise: [e.g. v4.9.0 or v4.10.0]

**Screenshots**
<img width="823" alt="image" src="https://github.com/infor-design/enterprise-wc/assets/56722184/8c72f81c-ca1f-4d9f-97f6-78808c084033">

**Platform**
Safari

**Additional context**

**Comment by n-ace-ancog** [comment] 2024-07-08 10:43
Duplicate of #2522.

**Closed** 2024-07-08 13:05 UTC
