### ISSUE TITLE
IdsAppMenu: More button issue - BETA 1.3

### ISSUE THREAD

**Issue by glenlieorillo** [infor-design/enterprise-wc#2542] opened 2024-07-08 08:15 UTC
**Describe the bug**
More button is not properly placed when the app menu is expanded.

**To Reproduce**

1. Go to https://main.wc.design.infor.com/ids-app-menu/example.html
2. Click on `menu` button to expand the app menu
3. Click on `more` button

**Expected behavior**

**Version**

- ids-enterprise: [e.g. v4.9.0 or v4.10.0]

**Screenshots**
![image](https://github.com/infor-design/enterprise-wc/assets/102151352/65769ca9-7bad-491f-a7b0-e40e1961a01e)

**Platform**
 - All major browsers

**Additional context**

**Comment by tmcconechy** [comment] 2024-07-24 17:55
Closing as duplicate of https://github.com/infor-design/enterprise-wc/issues/2543

**Closed by tmcconechy** 2024-07-24 17:55 UTC
Labels: type: bug :bug:, status: duplicate :twisted_rightwards_arrows:, [2]
