### ISSUE TITLE
IdsMenuButton/IdsPopupMenu: Popup menu position is off after latest upgrade in angular

### ISSUE THREAD

**Issue by ShwetaKhera** [infor-design/enterprise-wc#2013] opened 2024-03-07 22:12 UTC
**Describe the bug**
After the latest upgrade (version: `1.0.0-beta.21`) in angular, the position of popup menu overlaps its menu-button 
<img width="318" alt="Screenshot 2024-03-07 at 1 59 06 PM" src="https://github.com/infor-design/enterprise-wc/assets/30701871/f02dd4b9-b824-4cae-818e-43bbf2de8b68">
<img width="312" alt="Screenshot 2024-03-07 at 1 59 26 PM" src="https://github.com/infor-design/enterprise-wc/assets/30701871/f860b241-a3fc-4407-88b3-1dd67defd1c4">

**To Reproduce**

Requires basic implementation of ids-menu-button and ids-popup-menu in angular. Serve the angular app and click on the menu.

**Expected behavior**
The position of popup menu should be below menu-button

**Version**

- ids-enterprise: 1.0.0-beta.21
- Angular: ^17.2.3

**Platform**
 - Infor Application/Team Name: Infor Birst - ETLP Team
 - Browser Name: chrome

**Comment by tmcconechy** [comment] 2024-03-08 15:38
@ShwetaKhera I can't reproduce this. What do we need to be able to reproduce? Can you modify the example to show the issue? I recently fixed a bug here.

Try to pull the latest on https://github.com/infor-design/enterprise-wc-examples/tree/main/angular-ids-wc
Then do `npm i` and run http://localhost:4200/ids-menu-button/example

Looks ok:
![Screenshot 2024-03-08 at 10 37 35 AM](https://github.com/infor-design/enterprise-wc/assets/814283/71621bba-f5a3-451d-9cac-a2beac7c70e6)

Its possible this fix isnt in beta.21 tho. So do confirm and we can see.

**Comment by tmcconechy** [comment] 2024-03-08 16:46
@ShwetaKhera but i was not able to reproduce. My assumption is your on an older version still? Try

```
cd folder where cloned
delete node_modules
git pull
npm i
npm run start
check menu button page
```

**Comment by tmcconechy** [comment] 2024-03-08 19:31
OK confirmed this was fixed on https://github.com/infor-design/enterprise-wc/issues/1804 and will be in beta 22 (the 15gh of March).

Sorry i was running "bleeding edge" with this fix so thought it was already released first.

<img width="188" alt="Screenshot 2024-03-08 at 2 30 31 PM" src="https://github.com/infor-design/enterprise-wc/assets/814283/c7d91336-13ca-464c-8f5b-2449f900d958">

**Closed by tmcconechy** 2024-03-08 19:31 UTC
Labels: type: bug :bug:, [2]
