### ISSUE TITLE
List view integration with virtual scroll

### ISSUE THREAD

**Issue by vamsiprathipati** [infor-design/enterprise-wc#2321] opened 2024-05-16 09:52 UTC
**Description**
I'm trying to integrate List view component with virtual scroll, I implemented virtual scrolling, but upon inspecting the elements in the developer tools, I noticed that all elements are still being loaded instead of just the visible ones.

**To Reproduce** 
<ids-list-view>
<ids-virtual-scroll #virtualScroll1 height="100vh" id="virtual-scroll-1" item-height="20" buffer-size="3" item-count="1000"> 
<div class="ids-list-view"> 
<div class="ids-list-view-body" part="contents"> 
<ids-list-view-item>
    <list-view-item>]
              .
              .
               .
 </list-view-item>
          .
          .
          .
   <list-view-item>
              
 </list-view-item>
</ids-list-view-item>
</div>
</div>
</ids-virtual-scroll>
</ids-list-view>

**Steps to reproduce the behavior:**
 1. Create a list view component
 2. Add some list view items as shown above
 3. Integrate virtual scroll with list-view
 
**Expected behavior**
 Virtual scroll should be applied and only visible items are loaded 

**Version**
ids-enterprise: ^1.0.0

**Comment by tmcconechy** [comment] 2024-05-16 11:49
duplicate of https://github.com/infor-design/enterprise-wc/issues/2322

**Closed by tmcconechy** 2024-05-16 11:49 UTC
