### ISSUE TITLE
Soho DataGrid Bug in pagination & personalize column 

### ISSUE THREAD

**Issue by sofien-chaouch-infor** [infor-design/enterprise-wc#1387] opened 2023-07-17 13:08 UTC
**Describe the bug**
1- after changing row height , pagination do not work.
2- after changing row height  **  or clicking on edit mode , the last or all personalize columns removed

**To Reproduce**

1. Add personalize columns
2. Go to change row height
3. choose a row height
4. see the changes (issues declared)

**Expected behavior**
Pagination works and personalize still shown
**Version**

- ids-enterprise: [v14.1.13]

**Screenshots**

**Platform**
 - Infor Application/Team Name: RMS]
 - Device: (if applicable) [All]
 - OS Version: [All]
 - Browser Name: [All

**Comment by tmcconechy** [comment] 2023-07-17 13:10
Im not following this issue. If i try the steps as listed on this example everything seems to be working ok https://main-enterprise.demo.design.infor.com/components/datagrid/example-paging.html

Can you clarify the bug? Also your version is rather old so do try it on the latest version first to see if its already fixed

**Comment by tmcconechy** [comment] 2023-09-05 17:30
cc @sofien-chaouch-infor see above

**Comment by tmcconechy** [comment] 2023-09-15 19:48
Closing this issue. Either it was in the wrong repo or I can follow and reproduce.

**Closed by tmcconechy** 2023-09-15 19:48 UTC
Labels: type: bug :bug:, status: clarification :question:, [3]
