### ISSUE TITLE
IdsMenuButton: popup menu out of placement in enterprise-ng modal

### ISSUE THREAD

**Issue by guoliang** [infor-design/enterprise-wc#2718] opened 2024-08-13 08:37 UTC
**Describe the bug**
I haven't tried it in the web component variant of modal, but for the modal from `enterprise-ng` it does not position correctly

![image](https://github.com/user-attachments/assets/16c641c6-3b3e-4441-afca-08a69dbb25bd)

**Expected behavior**
Popup menu should be below the menu button

**Version**

- ids-enterprise: 1.4.2

**Comment by tmcconechy** [comment] 2024-08-13 12:50
I think this is a duplicate of https://github.com/infor-design/enterprise-wc/issues/2682
One thing if the offset is consistent you can try is this setting we needed for this use case: https://main.wc.design.infor.com/ids-popup-menu/in-offset-container.html

**Comment by guoliang** [comment] 2024-08-13 13:08
for what it's worth, this wasn't an issue in `1.3.0`

**Comment by tmcconechy** [comment] 2024-08-13 13:11
If thats the case might want to set the `positionStyle` which we defaulted to `fixed` https://github.com/infor-design/enterprise-wc/blob/main/src/components/ids-popup-menu/ids-popup-menu.ts#L540

I think it was absolute before?

**Comment by guoliang** [comment] 2024-08-13 13:30
setting `position-style="absolute"` works, but feels like a confusing setting to use.

that needs to be set when in a modal, at least in `enterprise-ng` modal. and it is fine to use the current default for it when the popup-menu isn't used inside a modal.

**Comment by tmcconechy** [comment] 2024-08-28 12:55
Should be fixed by #2682

**Closed by tmcconechy** 2024-08-28 12:55 UTC
Labels: type: bug :bug:, [3], team: OAD
