### ISSUE TITLE
LineChart: Auto size based on values on X/Y axis

### ISSUE THREAD

**Issue by RaveendraPalem** [infor-design/enterprise-wc#1475] opened 2023-09-12 05:33 UTC
Line chart graph on is not visible after initial load when zoom out we can able to see the graph clearly.

Example : I have values [0,50,100,150,200,250] on Y axis and need to represent 275 at this point dot not visible when zoom out it's visible. one more thing 300 is not represented on Y axis.

Line chart would work like bar chart. On y axis we have 7k and top most values for June 6500.
Graph should display next value on the Y- axis based on the top most in the list.
https://main.wc.design.infor.com/ids-bar-chart/example.html

Default view
<img width="365" alt="image" src="https://github.com/infor-design/enterprise-wc/assets/144761991/bf849971-6f5f-447a-8560-00e564f3c7a3">

After Zoom out
<img width="492" alt="image" src="https://github.com/infor-design/enterprise-wc/assets/144761991/6f567d6f-e065-4e0f-8457-c4e94508b083">

**Comment by tmcconechy** [comment] 2023-09-12 12:46
Not sure 100% I follow the request is here? @RaveendraPalem Can you explain it another way? Maybe a mock up of what you want?

Did you really want this https://github.com/infor-design/enterprise-wc/issues/1458 ?

**Comment by alixrosales** [comment] 2023-09-18 17:58
@tmcconechy - Here is the Jira ticket that has steps to reproduce: https://jira.infor.com/browse/ICP-3272
The issue is that it auto-resizes. You can look in the Jira ticket at the 3rd screenshot that shows that the line stops at the top without showing what the value is.

**Comment by tmcconechy** [comment] 2023-09-18 18:02
@alixrosales thanks but we dont have access to that application or whatever it is. We would need a reduced test case.
Without being able to reproduce it in our components its hard to fix.

https://www.browserstack.com/guide/test-case-reduction-and-techniques#:~:text=Test%20Case%20Reduction%2C%20as%20the,suites%20for%20the%20Development%20team.

Might be as simple as dropping the test data and making a div the same size in https://stackblitz.com/edit/ids-enterprise-4870?file=index.js

**Comment by tmcconechy** [comment] 2024-06-07 13:43
@RaveendraPalem any more info you can provide to reproduce before we close this?

**Comment by RaveendraPalem** [comment] 2024-06-11 04:00
Hi Team,

Please close this for now if anything we will request you.
Thanks for your follow up.


Thanks & Regards,
Raveendra Palem

**Closed** 2024-06-11 13:19 UTC
Labels: type: enhancement :sparkles:, status: clarification :question:, [3]
