### ISSUE TITLE
IdsDataGrid delete row doesn't work properly

### ISSUE THREAD

**Issue by tenacity00** [infor-design/enterprise-wc#2501] opened 2024-06-27 12:17 UTC
**Describe the Issue**
IdsDataGrid delete row doesn't work properly. Pressing the delete button only deletes the first row, but it could delete the selected row upon pressing it again.

**To Reproduce**
Steps to see the question or problem:
1. Check row 105 to select it
2. Press the delete button
3. Notice the wrong row is deleted.

This can be replicated on the demo site:
https://main.wc.design.infor.com/ids-data-grid/editable-lookup.html

**Comment by tmcconechy** [comment] 2024-06-27 14:59
@tenacity00 can you clarify the steps? The way this example is working is whatever rows are selected and you hit delete it will remove them. But its just an example and not the only way you can implement it.

But i tried to follow the above and didnt get the issue. I tried to delete second row and other rows and it always seemed to delete what is selected so i think we need more help with the steps?

**Comment by tenacity00** [comment] 2024-06-27 15:14
Hi @tmcconechy , I recorded the steps I made on your demo site. please check. 
[datagrid delete issue.zip](https://github.com/user-attachments/files/16016155/datagrid.delete.issue.zip)

Thanks

**Comment by tmcconechy** [comment] 2024-07-09 19:17
@tenacity00 if needing a workaround i found out the problem is that if there is no `id` column the logic wont work correctly So you can try to set `idColumn` to your field that acts as a primary key or add data in an `id` column.

Then i think we can update the logic but there are some other cases that require a primary key

**Comment by tmcconechy** [comment] 2024-07-09 19:27
fixed on PR on the linked issue

**Closed by tmcconechy** 2024-07-09 19:27 UTC
Labels: type: bug :bug:, status: duplicate :twisted_rightwards_arrows:, [3]
