### ISSUE TITLE
IdsDataGrid tree grid virtual/infinite scroll missing rows

### ISSUE THREAD

**Issue by jdilag90** [infor-design/enterprise-wc#1472] opened 2023-09-11 17:57 UTC
**Describe the bug**
In the [tree grid virtual/infinite scroll example](https://main.wc.design.infor.com/ids-data-grid/tree-grid-virtual-scroll-infinite-scroll.html), some collapsed rows go missing after infinite-scroll

**To Reproduce**
1. Go to https://main.wc.design.infor.com/ids-data-grid/tree-grid-virtual-scroll-infinite-scroll.html
2. Note that row column #'s are sequential
3. Collapse rows 6, 9, 12, 18
4. Scroll down to about row 450
5. Scroll back up to top
6. Expand rows 6, 9, 12, 18
7. See that some rows are missing by finding gaps in row column #'s 
8. You might have to retry steps 1-7 a few times to see this happen

**Version**
- ids-enterprise-wc: v1.0.0-beta.15

**Screenshots**
Before Scrolling
![tgvsis-before](https://github.com/infor-design/enterprise-wc/assets/98347152/8d44cfb5-0a62-472b-b68b-a396c4949315)

Vs. After Scrolling (Notice rows 14, 15 are missing)
![tgvsis-after](https://github.com/infor-design/enterprise-wc/assets/98347152/1fbd4e5f-fba1-48bb-a109-3fa602d72577)

**Platform**
 - OS Version: Windows 11
 - Browser Name: Chrome
 - Browser Version: 116.0.5845.180 (Official Build) (64-bit)

**Additional context**
This only happens in the tree-grid-virtual-scroll-infinite-scroll.html example and not the [virtual scroll only example](https://main.wc.design.infor.com/ids-data-grid/tree-grid-virtual-scroll.html)

**Comment by clayinfor** [comment] 2023-10-16 20:01
Closing this  because I cannot reproduce, and it was likely resolved in my fix/refactor for in #1485

**Closed by clayinfor** 2023-10-16 20:01 UTC
Labels: type: bug :bug:, [3]

**Comment by glenlieorillo** [comment] 2023-10-17 09:18
Passed.


https://github.com/infor-design/enterprise-wc/assets/102151352/e98cd6d7-dbb1-4b40-8224-7eb9dc66e7d5
