### ISSUE TITLE
Add any icons to be an alert icon

### ISSUE THREAD

**Issue by ali-zheng** [infor-design/enterprise-wc#1160] opened 2023-02-28 20:06 UTC
**Is your feature request related to a problem or use case? Please describe.**
We have a requirement to update the icon colour based on different statuses in the calendar web component. At this time, for an icon component in the web component library, there is no colour control tied to it. While for Alert icons, we can define the colour of the icon.

**Describe the solution you'd like**
we are looking to have the ability to add any icons (from IDS or customized) as an alert icon, and hence control the colour of the icon. The colour can stay static and follow IDS colour suggestions. 

**Describe alternatives you've considered**
or add a colour control to the existing icon component

**Additional context**
Current IDS wc icon:
<img width="598" alt="image" src="https://user-images.githubusercontent.com/125396779/221956623-001f9ef5-b8f2-4d5f-8831-a495d636901d.png">
IDS wc alert icon:
<img width="591" alt="image" src="https://user-images.githubusercontent.com/125396779/221956810-13c9742b-3a9d-4446-ba00-4820c1d64c34.png">

And what application do you work on? WFM

cc: @LilBiggs

**Comment by tmcconechy** [comment] 2023-02-28 21:38
Duplicate of https://github.com/infor-design/enterprise-wc/issues/1138

I added this ability already...And its merged and in beta.7

```
<ids-alert icon="calendar" color="info" tooltip="Calendar Alert"></ids-alert>
<ids-alert color="error" tooltip="Blood Alert" size="small"></ids-alert>
```

https://github.com/infor-design/enterprise-wc/pull/1139

**Closed** 2023-02-28 21:42 UTC
Labels: type: bug :bug:, status: duplicate :twisted_rightwards_arrows:, [2], team: WFM
