### ISSUE TITLE
IdsTooltip: not aligned in safari

### ISSUE THREAD

**Issue by jbrcna** [infor-design/enterprise-wc#1810] opened 2024-02-01 06:49 UTC
**Describe the bug**

**To Reproduce**

1. Go to https://main.wc.design.infor.com/ids-tooltip/sandbox.html
2. Scroll to the very bottom of page and verify that TOOLTIPS (WHEN ELLIPSIS TEXT) section works properly.

**Expected behavior**
tooltip should be properly aligned according to its placement
<img width="562" alt="image" src="https://github.com/infor-design/enterprise-wc/assets/56722184/121e6688-498c-4e6c-9490-363d8cae4f2b">

**Version**

- ids-enterprise: [e.g. v4.9.0 or v4.10.0]

**Screenshots**
<img width="738" alt="image" src="https://github.com/infor-design/enterprise-wc/assets/56722184/7e081e7e-bcf0-46fd-926d-6566ce1d0613">

**Platform**
Safari

**Additional context**
related  to https://github.com/infor-design/enterprise-wc/issues/1639

**Comment by jmacaluso711** [comment] 2024-04-03 19:20
@jbrcna I can't reproduce this bug on Safari v17.4.1 - Was there a specific version of Safari that you were seeing this? It could be that this issue was fixed in another PR

**Comment by jbrcna** [comment] 2024-04-04 09:00
Hi @jmacaluso711 this seems to be working now. 
<img width="1220" alt="image" src="https://github.com/infor-design/enterprise-wc/assets/56722184/4dc8905f-5a94-440f-a80e-5a028f0c50ed">
my safari version is 
<img width="239" alt="image" src="https://github.com/infor-design/enterprise-wc/assets/56722184/11f8c536-b00f-4623-9ebc-781f4d4d339e">

**Closed** 2024-04-11 12:19 UTC
Labels: type: bug :bug:, [2]
