### ISSUE TITLE
IdsCheckBoxGroup: IdsCheckboxGroup.value method doesn't update the attribute values of the checkboxes when set to true

### ISSUE THREAD

**Issue by n-ace-ancog** [infor-design/enterprise-wc#2020] opened 2024-03-11 03:21 UTC
**Describe the bug**
Changing the `ids-checkbox` values to `true` inside a `ids-checkbox-group` via `IdsCheckboxGroup.value` doesn't update the attribute of the elements. 

**To Reproduce**
1. Go to https://main.wc.design.infor.com/ids-checkbox-group/example.html
2. Open the developer's console
3. Type `document.querySelector('ids-checkbox-group').value = true` or `document.querySelector('ids-checkbox-group').value = [true, true, true]` and enter
4. The 1st checkbox is checked
5. Inspect and check the attribute values for the 1st checkbox, its still `checked=false`
6. Type `document.querySelector('ids-checkbox[label="Option 1"]').checked` and enter
7. It returns `false` rather than `true`

**Expected behavior**
The checkbox should be selected as well the attributes are updated.

**Version**
- ids-enterprise-wc

**Screenshots**
**via Boolean**
![Animation](https://github.com/infor-design/enterprise-wc/assets/156752175/238d735c-55bd-431d-b7d0-ad166c7e76df)

**via Array**
![Animation](https://github.com/infor-design/enterprise-wc/assets/156752175/c79842d7-4f5a-4d01-81b7-b54a37d21b34)

**Comment by tmcconechy** [comment] 2024-04-01 17:05
Found this is a duplicate of https://github.com/infor-design/enterprise-wc/issues/2027

**Closed** 2024-04-03 18:52 UTC
Labels: type: bug :bug:, [2]

**Comment by jbrcna** [comment] 2024-04-16 01:28
QA Failed
<img width="1715" alt="image" src="https://github.com/infor-design/enterprise-wc/assets/56722184/349df30b-1ec4-4d34-a7b2-2564ee5f80d4">
checkbox does not update
<img width="1676" alt="image" src="https://github.com/infor-design/enterprise-wc/assets/56722184/afe39dd2-95f2-4079-a0fd-fd3a485a38ba">
