### ISSUE TITLE
IdsPopupMenu: Add setting to set the position style

### ISSUE THREAD

**Issue by radovaniljic** [infor-design/enterprise-wc#2289] opened 2024-05-06 07:48 UTC
**Is your feature request related to a problem or use case? Please describe.**
When using `IdsPopupMenu`, the `IdsPopup` that the component uses is absolutely positioned, which causes an issue when the menu has an ascendant which is relatively positioned since the menu will be contained within the ascendant, but the position of the menu seems to be based on the `IdsContainer`, which causes the menu to be clipped in this scenario. Here's an example in OS Portal:

![containers](https://github.com/infor-design/enterprise-wc/assets/63045013/595068da-6489-4b44-934b-b3c2523d8c4f)
![menu](https://github.com/infor-design/enterprise-wc/assets/63045013/3f2d2d90-b340-4b6f-bc06-58403fa3a2dc)

Stackblitz: https://stackblitz.com/edit/ids-enterprise-wc-100-57mcqe?file=index.html

**Describe the solution you'd like**
`IdsPopup` has a setting `positionStyle` where you can set how it should be positioned, `IdsPopupMenu` should have the same setting.

**Describe alternatives you've considered**

1. Setting `overflow-x: auto` on the ascendant that's relatively positioned. This makes it possible to actually see the entire menu, but the scrollbar makes it ugly and awkward.
![overflow_auto](https://github.com/infor-design/enterprise-wc/assets/63045013/0cf525a6-5f8a-4593-ba64-e90d844b0fff)
2. Manually setting `positionStyle` on the `IdsPopup` via the `IdsPopupMenu`: 
`document.querySelector("ids-popup-menu").popup.positionStyle = "fixed"` (or using viewchild)
This works but 
a) we use Angular and would prefer to not do this. Being able to pass it as an input to the component would be much better: 
`<ids-popup-menu positionStyle="fixed"></ids-popup-menu>`
b) the menu gets misaligned at the top:
![misaligned](https://github.com/infor-design/enterprise-wc/assets/63045013/0e440783-0a82-472c-86eb-58ccf077a268)

**Additional context**
And what application do you work on? `OS Portal`

**Comment by tmcconechy** [comment] 2024-05-06 13:39
1. Should fix with https://github.com/infor-design/enterprise-wc/issues/2285
2. We should consider if `fixed` will work as a better default

**Comment by tmcconechy** [comment] 2024-05-16 20:04
@radovaniljic Quick question on this. Are you going to need to set the `position: relative` on the container or is that just part of the example. Because it messes up the position of fixed in the popup.

I can either ignore that or fix for that case (which could be a little tricky).  So just want to check `position: relative` is really needed on that parent div?

**Comment by radovaniljic** [comment] 2024-05-17 06:49
@tmcconechy we do have `position: relative` on that green container that you can see in the first two screenshots in OS Portal, but we haven't migrated all of that to Web Components yet so we might not need it later. It's unfortunate that the positioning doesn't work with `position: relative` since quite common to use, but if it's too tricky to fix I guess we have to accept that and avoid using it if possible.

**Comment by tmcconechy** [comment] 2024-05-17 13:07
@radovaniljic let me check this some more, may be able to fix. Also its effecting submenus so that needs checking along side.

**Comment by anhallbe** [comment] 2024-05-20 17:03
FYI I run into this issue (and similar ones) quite often, where I want some IDS component that depends on popup, in a context where at least one of the containing nodes have some special positioning (and / or overflow). Here's a test page with combinations of `position` and `overflow`:

https://stackblitz.com/edit/vite-gafwjz?file=index.html

<img width="678" alt="image" src="https://github.com/infor-design/enterprise-wc/assets/4991954/e84c49ed-8287-4128-9c45-f9ee869477bb">

<img width="678" alt="image" src="https://github.com/infor-design/enterprise-wc/assets/4991954/74e3e5dd-f8ef-4e25-b1bd-be49292895e1">

<img width="678" alt="image" src="https://github.com/infor-design/enterprise-wc/assets/4991954/d80b4487-3cf1-4567-98fe-5a7871e5acc5">

<img width="678" alt="image" src="https://github.com/infor-design/enterprise-wc/assets/4991954/0f1afcba-09a0-4729-bb38-74290bb68d8f">

**Comment by tmcconechy** [comment] 2024-05-20 17:09
@anhallbe the issue is fixed on the PR attached. Rather than saying we can fix it so the popupmenu will work in every possible position (it wont especially for overflow on). We changed it to fixed which solved the overflow issue. So should be resolved.

Issue is approved, merging and will add it to `1.1.1` patch soon. Can have a look if you want at the PR. https://github.com/infor-design/enterprise-wc/pull/2330

**Closed** 2024-05-20 19:17 UTC
Labels: type: bug :bug:, [2]

**Comment by anhallbe** [comment] 2024-05-21 09:17
Accidentally wrote as comment in the PR, adding it here for visibility:

> @tmcconechy I checked out the main branch & tried it in Portal.
> 
> The `<ids-tab-more>` was one of the components that previously didn't work because of this issue. Now, it works slightly better but the fixed positioning together with `top:0; left: 0` still causes the popup to be misplaced:
> 
> <img alt="image" width="2000" src="https://private-user-images.githubusercontent.com/4991954/332360569-888224c6-beee-430e-8485-513227354808.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYyODI5MjYsIm5iZiI6MTcxNjI4MjYyNiwicGF0aCI6Ii80OTkxOTU0LzMzMjM2MDU2OS04ODgyMjRjNi1iZWVlLTQzMGUtODQ4NS01MTMyMjczNTQ4MDgucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDUyMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA1MjFUMDkxMDI2WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YzRhNDk0N2E1NzZhNTkwZWEzMjU4YTQwYzc2NGIzNmZhYzJhMmY2MWE0YTUwNWZmYzIwOWIzYmQ1ZjczMWNiNCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.QFVjZQ_DNZRoWsNie4O825yT7iySCiTbQ6eagtmUwAU">
