### ISSUE TITLE
IDSMenuButton - Popup should display in correct position.

### ISSUE THREAD

**Issue by Varalaxmi26** [infor-design/enterprise-wc#2669] opened 2024-08-02 16:12 UTC
The popup is not displaying in correct when click on IDS Menu button. Pop up is displaying on top the settings menu button.  Popup position got changed. 

**To Reproduce**
It is directly reproducible in the angular example project in the enterprise-wc-examples\angular-ids-wc>

**Expected behavior**
IDSMenuButton - Popup should display in correct position.

**Version**
"ids-enterprise-wc": 1.4.0

**Screenshots**
![image](https://github.com/user-attachments/assets/23ec4c22-79c6-42d4-b160-f72399f22ff1)

**Platform**
 - Infor Application/Team Name: Notification Center

**Comment by tmcconechy** [comment] 2024-08-02 16:35
@andriivarhanov @jdilag90 

Was this recently fixed or am I recalling incorrectly?

**Comment by andrivarhanov** [comment] 2024-08-02 16:46
@tmcconechy can confirm the issue is there for Angular examples, just checked. I was working well a couple months ago, there were some changes probably

**Comment by tmcconechy** [comment] 2024-08-02 16:49
ok thanks can you talk a look. Might be more important then the new sprint issues?

**Comment by andrivarhanov** [comment] 2024-08-02 16:52
@tmcconechy sure, on it

**Comment by guoliang** [comment] 2024-08-05 15:07
Are you going to build `1.4.2` with a fix, or do we need to wait until the next minor release?

**Comment by tmcconechy** [comment] 2024-08-05 15:15
@guoliang 

Sure. We can make a patch if thats what you want @guoliang ? Would include all fixes from 1.4.1 though (just a few  https://github.com/infor-design/enterprise-wc/blob/main/doc/CHANGELOG.md#150-fixes) would like to get the tab one in anyways?

Just waiting for some QA

**Comment by guoliang** [comment] 2024-08-05 15:20
@tmcconechy nvm, I just saw that `1.5.0` was released. So, if this fix will be in patch release for it I'm good with that also.

**Comment by tmcconechy** [comment] 2024-08-05 15:23
@guoliang i'll make a 1.4.2 when its merged. 1.5.0 would maybe be a month or so away (its easy enough to do now)

**Closed** 2024-08-06 14:18 UTC
Labels: type: bug :bug:, [2], High

**Comment by guoliang** [comment] 2024-08-07 09:54
@tmcconechy saw that it was merged. will `1.4.2` be available later this week?

**Comment by tmcconechy** [comment] 2024-08-07 14:05
@guoliang yes very soon have one more fix to merge for another team

**Comment by anhallbe** [comment] 2024-08-21 07:35
@tmcconechy @andrivarhanov FYI I *think* the fix for this caused a new issue: https://github.com/infor-design/enterprise-wc/issues/2747
