### ISSUE TITLE
IdsDropdown: Drop menu does not have same size as dropdown component

### ISSUE THREAD

**Issue by guoliang** [infor-design/enterprise-wc#2435] opened 2024-06-10 11:09 UTC
**Describe the bug**
![image](https://github.com/infor-design/enterprise-wc/assets/542598/20d1f50a-3ef1-4ebf-9828-fc3ff794be78)

**To Reproduce**

1. Add `size="full"`
2. Click on dropdown element

**Expected behavior**
Drop menu should have the same width as dropdown element

**Version**

- ids-enterprise: 1.2.0

**Comment by tmcconechy** [comment] 2024-06-10 13:23
I think this is a duplicate of https://github.com/infor-design/enterprise-wc/issues/2001 moved it in the more important bucket

**Comment by guoliang** [comment] 2024-06-10 13:57
> I think this is a duplicate of #2001 moved it in the more important bucket

Yes looks to be same. This one can be closed then.

**Closed** 2024-06-10 13:58 UTC
Labels: type: bug :bug:, [2]
