### ISSUE TITLE
IdsPopupMenu: Incorrect events bound to submenu items

### ISSUE THREAD

**Issue by EdwardCoyle** [infor-design/enterprise-wc#525] opened 2022-01-28 15:53 UTC
**Describe the bug**
IdsMenuItem components that contain submenus (IdsPopupMenu) incorrectly have both `contextmenu` and `click` events bound.  When clicking the parent menu item of an already-opened submenu, the conflict can cause that submenu to become incapable of being opened again.

**To Reproduce**
1. Go to https://main.wc.design.infor.com/ids-popup-menu/
2. Right click anywhere to open the context menu
3. Hover the "More Actions" menu item and wait for its submenu to open
4. Click the "More Actions" menu item.  Its submenu flashes open and closed again
5. Try clicking or hovering to open the "More Actions" submenu again.  It's now impossible to open

**Expected behavior**
- [ ] Menu items should open on click, or after a delay during hovering.  
- [ ] Clicking the menu item after the submenu opens shouldn't cause any placement or visibility issues with the menu.

**Additional context**
- This is likely caused by `IdsPopupInteractionsMixin` not having a `hover` setting...
- ...and the default `contextmenu` event from the mixin still fires even after the IdsPopupMenu's built in hover finishes.
- solving this may be implementing `hover` into IdsPopupInteractionsMixin and removing the built-in event handling from IdsMenuItem.
- Adding `hover` to the mixin may conflict with the behavior of IdsTooltip (also has a built-in event handler for hover) -- will need to test this as well.

**Comment by tmcconechy** [comment] 2022-01-28 16:50
Is this really a duplicate of https://github.com/infor-design/enterprise-wc/issues/512 and can that be closed then?

**Comment by EdwardCoyle** [comment] 2022-01-28 17:46
@tmcconechy Yeah this is pretty much the same issue.  It's not limited to the theme switcher -- present in all IdsPopupMenu components

**Closed** 2022-02-14 18:23 UTC
Labels: type: bug :bug:, [3]
